<?xml version="1.0"?>
<package format="3">
  <name>rtr_qr_reader</name>
  <version>0.0.0</version>
  <description>The rtr_qr_reader package</description>

  <maintainer email="hans@todo.todo">hans</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>jsk_rviz_plugins</build_depend>
  <build_depend>rclpy</build_depend>
  <build_export_depend>jsk_rviz_plugins</build_export_depend>
  <build_export_depend>rclpy</build_export_depend>
  <exec_depend>jsk_rviz_plugins</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <depend>rtr_msgs</depend>

  <export>
  </export>
</package>
